-- MySQL Script generated by MySQL Workbench
-- idconfiguracion- Sun Nov  6 15:51:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `idconfiguracion` INT NULL,
  `iddatossemaforo` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `mail` VARCHAR(255) NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamentos` (
  `iddepartamentos` INT NOT NULL AUTO_INCREMENT,
  `idconfiguracion` INT NULL,
  `idmunicipios` INT NULL,
  `nombredepartamento` VARCHAR(255) NULL,
  PRIMARY KEY (`iddepartamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`municipios` (
  `idmunicipios` INT NOT NULL AUTO_INCREMENT,
  `iddepartamentos` INT NULL,
  `idconfiguracion` INT NULL,
  `nombremunicipio` VARCHAR(255) NULL,
  PRIMARY KEY (`idmunicipios`),
  INDEX `FK_DepartamentosMunicipios_idx` (`iddepartamentos` ASC) ,
  CONSTRAINT `FK_DepartamentosMunicipios`
    FOREIGN KEY (`iddepartamentos`)
    REFERENCES `mydb`.`departamentos` (`iddepartamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`configuracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`configuracion` (
  `idconfiguracion` INT NOT NULL AUTO_INCREMENT,
  `idusuarios` INT NULL,
  `idmunicipios` INT NULL,
  `brillo` INT NULL,
  `contraste` INT NULL,
  `color` INT NULL,
  `modo` VARCHAR(45) NULL,
  `redneuronal` VARCHAR(45) NULL,
  PRIMARY KEY (`idconfiguracion`),
  INDEX `FK_UsuariosConfiguraion_idx` (`idusuarios` ASC) ,
  INDEX `FK_MunicipiosConfiguracion_idx` (`idmunicipios` ASC) ,
  CONSTRAINT `FK_UsuariosConfiguraion`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MunicipiosConfiguracion`
    FOREIGN KEY (`idmunicipios`)
    REFERENCES `mydb`.`municipios` (`idmunicipios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`datossemaforo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datossemaforo` (
  `idcarros` INT NOT NULL AUTO_INCREMENT,
  `idusuarios` INT NULL,
  `fecha` DATETIME(6) NULL,
  PRIMARY KEY (`idcarros`),
  INDEX `FK_UsuariosDatossemaforo_idx` (`idusuarios` ASC) ,
  CONSTRAINT `FK_UsuariosDatossemaforo`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `mydb`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
